### PR TITLE
fix missing user-installed fonts

### LINKED ISSUE #136: fontconfig user configuration
The Font Manager application allows you to activate fonts outside `~/.local/share/fonts`. We need to add `filesystem=xdg-config/fontconfig:ro` to the permissions to retrieve them in LibreOffice.

### PR DESCRIPTION
**Pull request by bam80**
Fixes #136

### CODE REVIEW

**Comment by stbergmann** [comment]
> All checks have failed

Appears to be due to `org.freedesktop.Sdk//22.08` having recently been updated from libxml2 2.10.3 to 2.10.4.  I'm taking care of that.

**Comment by stbergmann** [comment]
> Appears to be due to `org.freedesktop.Sdk//22.08` having recently been updated from libxml2 2.10.3 to 2.10.4. I'm taking care of that.

Please rebase this PR on top of master commit <https://github.com/flathub/org.libreoffice.LibreOffice/commit/0167589a0c1220f8992dc2b3289d993a49c1319f> "Fix broken LibreOffice test".

**Comment by stbergmann** [comment]
> Please rebase this PR on top of master commit [0167589](https://github.com/flathub/org.libreoffice.LibreOffice/commit/0167589a0c1220f8992dc2b3289d993a49c1319f) "Fix broken LibreOffice test".

@bam80 Can you please do that, so we can move forward here?

**Comment by bam80** [comment]
> > Please rebase this PR on top of master commit [0167589](https://github.com/flathub/org.libreoffice.LibreOffice/commit/0167589a0c1220f8992dc2b3289d993a49c1319f) "Fix broken LibreOffice test".
> 
> @bam80 Can you please do that, so we can move forward here?

Done.

Did you see the broken checks?
https://buildbot.flathub.org/#/builders/37/builds/4648

**Comment by stbergmann** [comment]
> Did you see the broken checks? https://buildbot.flathub.org/#/builders/37/builds/4648

The failed official master build for <https://github.com/flathub/org.libreoffice.LibreOffice/commit/0167589a0c1220f8992dc2b3289d993a49c1319f> "Fix broken LibreOffice test"?  Yes, I know.  That was apparently an intermittent outage on the TDF side, and is harmless:  The fix is known-good (the gating PR test build at <https://github.com/flathub/org.libreoffice.LibreOffice/pull/225> "Fix broken LibreOffice test" succeeded), it doesn't change the resulting flatpak (i.e., there is no benefit in pushing it to users now), and will be in place when the next LO flatpak version will be built.  So I simply silently left it at that failed master build.  But thanks for watching out.

**Comment by bam80** [comment]
> @bam80 Can you please do that, so we can move forward here?

Is it ready now to move forward?

**Pull request merged**
