### PR TITLE
Update to libreoffice-6.3.0.3

### PR DESCRIPTION
**Pull request by stbergmann**

### CODE REVIEW

**Comment by LeandroStanger** [comment]
bot, build org.libreoffice.LibreOffice

**Comment by go-ten** [comment]
Hi,
This update is not yet available on Flathub?

**Comment by Erick555** [comment]
Yes, official builds failed go date, current attempt is here: https://flathub.org/builds/#/builders/32/builds/6414

**Comment by stbergmann** [comment]
LO 6.3.0.4 should finally be available on Flathub now.

**Comment by go-ten** [comment]
Thanks, it works perfectly.

**Pull request merged**
