### PR TITLE
Incorporate changes from upstream libreoffice-6.0.0.3

### PR DESCRIPTION
**Pull request by stbergmann**
* Add JVM support to Flatpak
* Let flatpak-builder build .Debug extension
* Adapt to changes to external packages and extra fonts

### CODE REVIEW

**Comment by stbergmann** [comment]
bot, build

**Comment by nedrichards** [comment]
"]2;flatpak-builder: Downloading libreofficeFailed to download sources: module libreoffice: Sha256 not specified"

**Comment by stbergmann** [comment]
bot, build

**Comment by stbergmann** [comment]
bot, build

**Comment by stbergmann** [comment]
bot, build

**Comment by stbergmann** [comment]
bot, build

**Pull request merged**
