### PR TITLE
Add Finnish spell checker and hyphenation. Closes #122.

### LINKED ISSUE #122: Add Voikko for Finnish spell check
Could this flatpak be made to include the [Voikko](voikko/libreoffice-voikko) Finnish spell check tool?

### PR DESCRIPTION
**Pull request by jpakkane**
This adds the Voikko extension to the Flathub version of LO. This extension can _not_ be installed from the extension manager because it requires that the Voikko libraries and data files are built and installed on the system. Trying to do so anyway will make LO Writer crash immediately on startup.

To validate that the installation is working do the following:

- launch LO
- open extension manager
- the Voikko extension should be in the list of installed extensions
- click on "options"
- if the popup window has Finnish in the dictionary dropdown, everything should be fine

### CODE REVIEW

**Comment by stbergmann** [comment]
> This adds the Voikko extension to the Flathub version of LO. This extension can _not_ be installed from the extension manager because it requires that the Voikko libraries and data files are built and installed on the system. Trying to do so anyway will make LO Writer crash immediately on startup.

From where would one get a Voikko `oxt` extension file that could be (unsuccessfully) installed with LibreOffice's extension manager?

**Comment by jpakkane** [comment]
I think I got it [here](https://extensions.libreoffice.org/en/extensions/show/finnish-spell-checker-and-hyphenator-voikko) but looking at the page there does not seem to be a Linux version. I might have tried to install the Windows version on Linux. In any case the only way to fix the issue was to delete the extension from the Flatpak hidden directory.

**Comment by jpakkane** [comment]
Updated the Voikko lib to install with setuptools so it should keep on working with new Python releases. Tested to work with a local build.

**Comment by jpakkane** [comment]
All the things originally mentioned have been fixed. What changes does still need to get merged?

**Comment by stbergmann** [comment]
Sorry for not replying earlier.  When I first saw this PR, I wasn't too enthusiastic about adding yet another bunch of dependencies, "merely" for one specific extension that, for one reason or another, is "not behaving well" and cannot be used like other extensions.  I'll try to look into this later.

**Comment by stbergmann** [comment]
See <https://github.com/flathub/flathub/pull/2455> "org.libreoffice.LibreOffice.BundledExtension.Voikko" for the alternative approach of providing this functionality as a bundled extension (which partially reuses this PR's content; many thanks for your original work!).

**Comment by stbergmann** [comment]
> > This adds the Voikko extension to the Flathub version of LO. This extension can _not_ be installed from the extension manager because it requires that the Voikko libraries and data files are built and installed on the system. Trying to do so anyway will make LO Writer crash immediately on startup.
> 
> From where would one get a Voikko `oxt` extension file that could be (unsuccessfully) installed with LibreOffice's extension manager?

(<https://git.libreoffice.org/core/+/f989bd22cc3c80d3c5119e3de1a269ab9a80bd78%5E%21> "Catch exceptions when setting up linguistic extensions" should fix that, btw)

**Pull request closed without merging**
