### PR TITLE
Update to LibreOffice 24.2.0

### PR DESCRIPTION
**Pull request by stbergmann**

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build

**Comment by hfiguiere** [comment]
now it's an actual build failure.

**Comment by bbhtt** [comment]
A fix for the icon thing is in the linter waiting deployment. Please wait for a bit.

**Comment by stbergmann** [comment]
bot, build

**Comment by bbhtt** [comment]
It isn't deployed I'll ping when it is.

**Comment by bbhtt** [comment]
bot, build

**Pull request merged**
